### ISSUE TITLE
Enable discussions on this repo

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#16]
Some of these issues seem like they should be discussions.

**opinion time** I use discussions to _discuss ideas_ and then issues to _track todos_. In the spirit of this, around the time where I get "maybe consider this idea"-type posts/ideas, I usually enable the discussion tab. GitHub also has great integration for this workflow with a "Create Issue from Discussion" button!

**p.s.** also consider disabling the Projects tab if you're not using it? That's my ocd speaking.

I know you have your own workflow; if you prefer to keep all these text posts in Issues tab instead, that's OK too. ❤️

**Comment by spenserblack** [comment]
Done :+1:

**Comment by jcbhmr** [comment]
Would you also be so kind as to transfer #14 #11 and any other "consider X" issues to discussions? 🙏
