### ISSUE TITLE
Publish v0 tag

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#21]
Right now there's the following tags:

![image](https://user-images.githubusercontent.com/61068799/225416625-1a30e458-1710-48ce-9626-e4bd26edd809.png)

I think a v0 tag would be a good idea. It can be auto-generated by a manual release! All we need to do is _create_ a new release...

do this whenever a new fancy feature gets added, I guess? or do it manually.

**Comment by spenserblack** [comment]
:shrug: Don't really see the benefit of a `v0` tag for users TBH. Since anything in the `v0` range can break, but `v0.x` should be *pretty* stable, then using `@v0` is about as stable as using `@main`.

**Comment by jcbhmr** [comment]
Well, I know I wanted to use it in https://github.com/jcbhmr/.github/blob/main/.github/workflows/publish-wiki.yml lmao 🤷‍♂️

but yeah you're right that major/minor versions don't make as much sense in v0 since it's a free-for-all until v1 according to https://semver.org/#faq

> How should I deal with revisions in the 0.y.z initial development phase?
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

> How do I know when to release 1.0.0?
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

> Doesn’t this discourage rapid development and fast iteration?
> Major version zero is all about rapid development. If you’re changing the API every day you should either still be in version 0.y.z or on a separate development branch working on the next major version.

**Comment by jcbhmr** [comment]
For more information about releasing, it looks like github _official recommends using MAJOR, MINOR, and PATCH versions_! Cool! https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions

> Create a semantically tagged release. You may also publish to GitHub Marketplace with a simple checkbox. For more information, see "[Managing releases in a repository](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release)" and "[Publishing actions in GitHub Marketplace](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace#publishing-an-action)".

> When a release is published or edited, your release workflow will automatically take care of compilation and adjusting tags.

> We recommend creating releases using semantically versioned tags – for example, v1.1.3 – and keeping major (v1) and minor (v1.1) tags current to the latest appropriate commit. For more information, see "[About custom actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions)" and "[About semantic versioning](https://docs.npmjs.com/about-semantic-versioning).

they even recommend using https://github.com/JasonEtco/build-and-tag-action#readme for JavaScript actions to generate a dist folder _only for TAGS, but not main branches_ which I think is cool

**Comment by spenserblack** [comment]
Thanks for the research!

I'd think that an action referenced in the GitHub docs would have more stars. Guess a lot of people don't read the docs :cry: (to be fair, I didn't read a lot of them either :laughing:)
