### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#26]
Just to make it more inviting and stuffs like that. Also maybe add a contributing note to the bottom of the readme

/assign @jcbhmr

**Comment by spenserblack** [comment]
This and #24 could possibly be done together in the same PR. There's a lot of overlap between what settings go in `devcontainer.json` and what instructions go in `CONTRIBUTING.md`, like linters to use.

**Comment by jcbhmr** [comment]
related to #30 discussion
