### ISSUE TITLE
Add a header image to readme

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#39]
### Discussed in https://github.com/spenserblack/actions-wiki/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **jcbhmr** March 17, 2023</sup>
Something like this? Might want to make the filenames actually line up, but the quick "what does this action do" is nice. even if there's already a title, an image like this clearly gets across what this action does and would be a good addition IMO

![image](https://user-images.githubusercontent.com/61068799/225987228-827ccde8-0d5e-495f-aa1f-eefb87fc2e2c.png)

it's sort of like a blog post; they are better when they have an image, even if the image is only tangentially related to what the content is. I mean, just look at this: https://web.dev/blog/

![image](https://user-images.githubusercontent.com/61068799/225987799-03cc8e5b-ab53-4e35-a04a-acf99b2cf89a.png)

wtf are these images?! they have almost nothing to do with html or js, and yet it's _still better than just a plain text post_. it helps break it up, and adds some "oh yeah that one" sort of like a profile picture for the project. it's like a "meme" in the truest _technical_ sense of the definition.</div>

**Comment by spenserblack** [comment]
I'm debating if this should be a *header* (on its own line), or adjacent to some text, like the features list.

**Comment by jcbhmr** [comment]
imo `<div align=center>` with an image in it looks pretty good

![image](https://user-images.githubusercontent.com/61068799/226506220-8f3fce4a-ab49-4474-9de8-1c8b7d2d9ca5.png)

![image](https://user-images.githubusercontent.com/61068799/226506248-6bc48cbb-e8bd-4a9c-87aa-b285f3d65563.png)
