### ISSUE TITLE
Would you be interested in consolidating with Andrew-Chen-Wang/github-wiki-action ?

### ISSUE THREAD

**Issue by jcbhmr** [spenserblack/actions-wiki#8]
If we were to fix the following problems with https://github.com/Andrew-Chen-Wang/github-wiki-action that this repo https://github.com/spenserblack/actions-wiki has advantaged over it, would you @spenserblack be interested in consolidating the ecosystem?

Here's a list of things that https://github.com/Andrew-Chen-Wang/github-wiki-action **CANT DO NOW** but this repo can (you could advertise these on the readme!):

- [ ] push to an arbitrary repo https://github.com/spenserblack/actions-wiki/blob/main/action.yml#L7
- [ ] work on windows? i don't know that this is an issue since I haven't tested this. I'm going off of what was remarked on in https://github.com/spenserblack/actions-wiki/issues/4#issuecomment-1444982155
- [ ] use plain git commands to smartly avoid using rsync or similar

Would you be interested in collaborating with me to combine/interfold/whatever this repo, the git subtree trick from https://github.com/jcbhmr/publish-wiki-action-OLD and mash those changes into the https://github.com/Andrew-Chen-Wang/github-wiki-action ?

https://github.com/Andrew-Chen-Wang/github-wiki-action/discussions/19

If not, that's OK too. It's good to have competition in an ecosystem! ❤

**Comment by jcbhmr** [comment]
Actually, I think I'm going to close this (for now at least). If you want to do this at some point to consolidate the ecosystem, great! But for now, I think the goals between this and the Andrew-Chen-Wang/github-wiki-action don't _quite_ align perfectly.

Andrew-Chen-Wang/github-wiki-action: Be the "all in one" wiki action? I think? Not really entirely clear yet.... \
This repo: Push things to a wiki. That's it; but do it well. Is this correct?

**Comment by spenserblack** [comment]
>Push things to a wiki. That's it; but do it well. Is this correct?

Yup, I think that summarizes it well. In the workflow that I imagined when making this, `.github/wiki` would basically be the source of truth. The wiki would just be a method of displaying these documents.
