### ISSUE TITLE
Rewrite in TS/JS

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/actions-wiki#80]
See https://github.com/spenserblack/actions-wiki/discussions/66#discussioncomment-5660995

**Comment by jcbhmr** [comment]
I know I mentioned this before, but I've since improved the "deno_wrapper" project: https://github.com/jcbhmr/deno_wrapper

**Comment by jcbhmr** [comment]
btw what are you even rewriting? 🤔 Most of the stuff in this problem space is just going to be running bash commands in series, right? There's not a whole lot of string processing, output inspection, if checks, etc. There's **only four spots** where I can see logic that's not just **a literal sequence of shell commands** 😂

https://github.com/spenserblack/actions-wiki/blob/1181a523379aa9893d0a8d7e71f1382a506b273b/src/clone.sh#L6-L13

https://github.com/spenserblack/actions-wiki/blob/1181a523379aa9893d0a8d7e71f1382a506b273b/src/clone.sh#L28-L34

https://github.com/spenserblack/actions-wiki/blob/1181a523379aa9893d0a8d7e71f1382a506b273b/src/clone.sh#L47-L50

https://github.com/spenserblack/actions-wiki/blob/1181a523379aa9893d0a8d7e71f1382a506b273b/src/clone.sh#L101-L108

What I'm getting at is that I don't entirely know _why_ this is being rewritten in JS/TS when it's just going to be:

```js
const inputIgnore = core.getInput("ignore")
const inputToken = core.getInput("token")
process.env.GITHUB_TOKEN = inputToken

try {
  await $`gh auth setup-git`
  await $`git clone ${process.env.GITHUB_SERVER_URL}${inputRepository}.wiki.git ${process.env.GIT_DIR}`
  await fsPromises.writeFile(join(process.env.GIT_DIR, ".git/info/exclude"), inputIgnore)
} catch {
  rimraf(process.env.GIT_DIR)
}
```

# But
If there's some feature that you're planning on adding, **that's cool and interesting!** Like for instance auto preprocessing the markdown like https://github.com/impresscms-dev/strip-markdown-extensions-from-links-action/blob/main/src/index.ts ⬅ That's the cool stuff that needs Node.js to work well! Shell commands in a sequence... not really.

But that's my opinion. 🤷‍♀️

**Comment by spenserblack** [comment]
I find TS easier to contribute to, and also I think it's easier to write tests. That's my basic reasoning. Also, I think the language looks prettier 🙃

**Comment by jcbhmr** [comment]
> I find TS easier to contribute to, and also I think it's easier to write tests. That's my basic reasoning. Also, I think the language looks prettier 🙃

Sounds awesome! More tests is always better! 🎉

**Comment by jcbhmr** [comment]
> I know I mentioned this before, but I've since improved the "deno_wrapper" project: https://github.com/jcbhmr/deno_wrapper

Thought you might be interested to know that I have dog-fooded my own thing! 😊 https://github.com/jcbhmr/set-secrets-action

**Comment by spenserblack** [comment]
Interesting idea! I've repeated secrets among multiple repos sometimes, could be handy :+1:

**Comment by jcbhmr** [comment]
Turns out that https://github.com/Andrew-Chen-Wang/github-wiki-action needed the push to TS after all.  https://github.com/Andrew-Chen-Wang/github-wiki-action/pull/68 With https://github.com/Andrew-Chen-Wang/github-wiki-action/issues/8 you need an AST parser, and JavaScript has Markdown parsers in spades. I used a modified https://github.com/jcbhmr/deno_wrapper script `cliw` to then run `cli.ts` with **no build step** with a negligible runtime cost (there's enough GH Actions overhead that 400ms to download Deno+npm stuff doesn't matter)

Just figured you might be interested 😉
